### PR TITLE
Experimental UI changes

### PR DESCRIPTION
**Pull request by vaspa**
Could you check the changes?  Don't know if it will be easier to merge with master or redo the changes you made over this version...

Here is a brief list of changes:
- Some refactoring: fragment <-> activity
- New Navigation Drawer
- New icons
- A few UI changes: move to single toolbar, keep bottom status bar visible
- Vibrate on disconnection option
- OSSW runs in foreground service now
- Notification bar icon with connection status
- A few fixes

### CODE REVIEW

**Comment by althink** [comment]
Ok, I will check it today evening

**Comment by althink** [comment]
What I like:
- Moving list item actions to top toolbar
- Moving settings/exit to navigation bar
- Changing watchset import fragment to activity 

Some stuff that is more like "There is no accounting for taste":
- For me it's quite hard to read this green font on grey selection in navigation drawer
- Not quite get the concept of "Watches" screen, only one watch can be connected at a time so what is the profit to see connection status of every of them
- "Connected" string color on "Watches" screen does not match other colors, maybe it should be the same as bottom bar color.

What I dont't like:
- Auto reconnect is broken, when some watch is connected and app is restarted then watch is not automatically connected, simple use case is automatic update from play store, after app update your watch will be disconnected.
- When landscape/portait mode is switched on the main screen we're redirected to the "Watch faces" screen even if we were on different screen, code that handled that was removed.
- When you play with connect/disconnect phone sometimes vibrates (is it connection lost notification?) and app sometimes crashes
- Functionality that allows to deselect items on watch face list was removed, it's quite standard way of handling that in Android 5.0+ and don't know why it was removed. Also when we moved actions to top action bar I think that screen title should be hidden when actions are shown (like in GMail app ) because on my phone title is taking almost all available space.
- When you open "Watches" screen and go to settings from it then when you return it's empty
- I'm not quite sure if I like the fact that "Connected" bar is always shown, it's taking space and doesn't allow to do anything
- Small arrow on bottom bar most of the time does not work, I have to press it 10 times to see "Watches" screen
- App crashes quite often, sample stack traces:

11-18 23:00:00.797    7365-7365/com.althink.android.ossw E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.althink.android.ossw, PID: 7365
    java.lang.IllegalStateException: Content view not yet created
            at android.support.v4.app.ListFragment.ensureList(ListFragment.java:328)
            at android.support.v4.app.ListFragment.getListView(ListFragment.java:222)
            at com.althink.android.ossw.watchsets.WatchSetsFragment.resetSelection(WatchSetsFragment.java:118)
            at com.althink.android.ossw.watchsets.WatchSetsFragment.refreshWatchSetList(WatchSetsFragment.java:79)
            at com.althink.android.ossw.watchsets.WatchSetsFragment.onCreateOptionsMenu(WatchSetsFragment.java:69)
            at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2047)
            at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:2125)
            at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:270)
            at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:299)
            at android.support.v7.internal.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
            at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:243)
            at android.support.v7.internal.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
            at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:448)
            at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:65)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5294)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

11-18 23:34:54.703    8710-8710/com.althink.android.ossw E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.althink.android.ossw, PID: 8710
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
            at com.althink.android.ossw.DeviceScanFragment$3.onLeScan(DeviceScanFragment.java:294)
            at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:1825)
            at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:331)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5294)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

11-18 18:00:30.773    1921-1921/com.althink.android.ossw E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at com.althink.android.ossw.DeviceScanFragment.onCreateView(DeviceScanFragment.java:82)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by vaspa** [comment]
Great, useful feedback. Good that you liked most of new features and disliked the bugs and inconsistencies  ;-)
Obviously it is too buggy to merge. Will be fixing the bugs/broken stuff in the following evenings.
A real thing under question is the "Watches" fragment. My idea was about managing several OSSW (or other maybe) BLE devices from the App, so I converted device selection to a "management" view. Next step (not urgent) was to provide internal support for connecting/disconnecting multiple BLE devices.
Now I'm not sure if it will be useful or not. Anyway it can be transform back to "select and forget"...

BTW for clarification:
- What is the resolution of your device? 800x480 or 960x540? Thought my old 1280x720 was OK.
- You can't deselect items in watchset list after selecting them?

**Comment by vaspa** [comment]
Fixed several bugs. Now it is stable (on my smartphone).
- The new navigation drawer (Design Support Library) is almost declarative, had to add some code to the MainActivity to restore the state on orientation, because that code was in the old drawer before.
- Could not reproduce the selection/deselection bug on the watch faces page...
- Added the notification filtering preference to select from which applications we'll get the notifications (some default apps could be pre-added maybe).

Hope it will be also stable on other smartphones, so we could merge it with your bug fixes.
If it is OK, I'll try to fix the "Incoming call" notification problem, it is still missing in KitKat.

**Comment by althink** [comment]
I've merged current develop into your branch and fixed travis config. Travis build is still not passing because new SettingsActivity breaks lint check :)

Unexpected failure during lint analysis of SettingsActivity.java (this is a bug in lint or one of the libraries it depends on)
Location.create(Location.java:251)->EcjParser.getLocation(EcjParser.java:552)->JavaContext.getLocation(JavaContext.java:90)->PrivateResourceDetector.visitResourceReference(PrivateResourceDetector.java:134)

I will play with the app a little more in the evening, first impression is that it's quite stable and I cannot read bright yellow texts in Settings ;)

If you could add some icons to applications/utilities then it would be great.

**Comment by althink** [comment]
Now it's finally passing: https://travis-ci.org/ossw/ossw-android/builds/92997105

**Comment by althink** [comment]
- Small issue: sometimes it's not possible to go to "Watch faces" from "Watches" screen, nothing happens and you have to go to other screen and then "Watch faces" link works (maybe I've broke something with merge, don't know ;) )
- Maybe we should ask people on ossw-beta group what the think about this look:
  device-2015-11-24-085210

device-2015-11-24-085226

It's really hard to read this yellow on white on my phone. This OSSW text is also not perfect ;) Maybe we have there some designer or something ;)

**Comment by vaspa** [comment]
1. Ok, I'll take a look now at the code and check if it is due to merge or an existing bug. Can you remember how to reproduce it?
2. Yes, the yellow is horrible...LOL  Now I understand that Android fragmentation it is a real pain.
   At the moment if we have no urgent features so we can share ideas and choose a better variant. I've got some info how to normalize the UI a across different API versions, so I'll try to play with it today and tomorrow.
   In fact, I had no time yet to play with style, fonts and colors, it was a kind of sandbox where I've put the widgets (icons, text and preferences). I took the cyan and orange that you had previously. The rest is the base theme as I understand correctly. BTW I don't like this cyan on the black background.

To resume: it needs some work, we can post samples in this thread and discuss, feedback and brainstorming are welcome ;-)

And here is how it looks on my phone. Apart the text "OSSW" (both its color and its top which is cut-off) IMHO it is OK.

device-2015-11-24-213859 device-2015-11-24-214026

**Comment by vaspa** [comment]
Could you check the latest version on your phone?
- I've fixed a few bugs appeared after merging, some rotation bugs.
- Added a preview feature for imported watch faces
- Toolbar adjusts its height on orientation change.
- Also created a header image, emulator buttons, some new icons.

**Comment by althink** [comment]
I've just took a look and it looks nice. Like the apps/utils icons. Even logo is quite nice but still looks like done by technical person :D (I wouldn't do better though ;) ) Maybe it's just the too big space between letters or this font.

I think I'll merge it in few days. Just need to stabilise all firmware features and binary format (there were some changes to support conditional rendering, watchset model etc.) so I wouldn't have to send you fixed firmware every day ;)

It's quite stable, most of the bugs are fixed I think. Only phone rotation may crash the app. Few samples:

```
11-28 13:05:02.928 19771-19771/com.althink.android.ossw E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.althink.android.ossw, PID: 19771
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
                                                                              at com.althink.android.ossw.DeviceScanFragment$3.onLeScan(DeviceScanFragment.java:308)
                                                                              at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:1825)
                                                                              at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:331)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

```
11-28 13:14:04.129 30701-30701/com.althink.android.ossw E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.althink.android.ossw, PID: 30701
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{com.althink.android.ossw/com.althink.android.ossw.MainActivity}: android.view.InflateException: Binary XML file line #66: Error inflating class <unknown>
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
                                                                              at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3980)
                                                                              at android.app.ActivityThread.access$1000(ActivityThread.java:154)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                           Caused by: android.view.InflateException: Binary XML file line #66: Error inflating class <unknown>
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257)
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                              at com.althink.android.ossw.MainActivity.onCreate(MainActivity.java:132)
                                                                              at android.app.Activity.performCreate(Activity.java:5990)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
                                                                              at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3980) 
                                                                              at android.app.ActivityThread.access$1000(ActivityThread.java:154) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
                                                                           Caused by: java.lang.reflect.InvocationTargetException
                                                                              at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                              at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                              at com.althink.android.ossw.MainActivity.onCreate(MainActivity.java:132) 
                                                                              at android.app.Activity.performCreate(Activity.java:5990) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
                                                                              at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3980) 
                                                                              at android.app.ActivityThread.access$1000(ActivityThread.java:154) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
                                                                           Caused by: java.lang.OutOfMemoryError: Failed to allocate a 4423692 byte allocation with 2130172 free bytes and 2MB until OOM
                                                                              at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                              at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                              at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:608)
                                                                              at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
                                                                              at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:988)
                                                                              at android.content.res.Resources.loadDrawableForCookie(Resources.java:2621)
                                                                              at android.content.res.Resources.loadDrawable(Resources.java:2528)
                                                                              at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
                                                                              at android.widget.ImageView.<init>(ImageView.java:146)
                                                                              at android.widget.ImageView.<init>(ImageView.java:135)
                                                                              at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:60)
                                                                              at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
                                                                              at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:98)
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:926)
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:980)
                                                                              at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                            at android.support.design.internal.NavigationMenuPr
11-28 13:14:06.608 30701-30701/com.althink.android.ossw I/Process: Sending signal. PID: 30701 SIG: 9
11-28 13:14:06.738 5368-5368/com.althink.android.ossw.plugins.ipsensorman D/IpSensorManPluginService: onUnbind
```

```
11-28 13:15:26.728 4360-4360/com.althink.android.ossw E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.althink.android.ossw, PID: 4360
                                                                        java.lang.IllegalStateException: Content view not yet created
                                                                            at android.support.v4.app.ListFragment.ensureList(ListFragment.java:328)
                                                                            at android.support.v4.app.ListFragment.getListView(ListFragment.java:222)
                                                                            at com.althink.android.ossw.watchsets.WatchSetsFragment.resetSelection(WatchSetsFragment.java:141)
                                                                            at com.althink.android.ossw.watchsets.WatchSetsFragment.onCreateOptionsMenu(WatchSetsFragment.java:76)
                                                                            at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2047)
                                                                            at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:2125)
                                                                            at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:270)
                                                                            at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:299)
                                                                            at android.support.v7.internal.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
                                                                            at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:243)
                                                                            at android.support.v7.internal.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
                                                                            at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:448)
                                                                            at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:65)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Pull request merged**
